# Generated by Django 3.2.8 on 2021-12-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gempa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.FloatField()),
                ('Lon', models.FloatField()),
                ('Depth', models.FloatField()),
                ('Mag', models.FloatField()),
                ('Region', models.CharField(max_length=250)),
                ('Date', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Gempa',
            },
        ),
    ]
