# Generated by Django 3.2.8 on 2021-12-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gempaBumiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediksi_Gempa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.FloatField()),
                ('Lon', models.FloatField()),
                ('Mag', models.FloatField()),
                ('Depth', models.FloatField()),
                ('Score', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Prediksi_Gempa',
            },
        ),
    ]
